"""Generated by ``oak setup``. Drop into your backend project.

Ownership markers used throughout this file:
  # [USER]      you write this — domain logic, prompts, tools
  # [OAK]       oak primitives — keep as-is unless you know what you're doing
  # [FRAMEWORK] upstream agent framework (OpenHands)

Wiring picked:
  workspace   : E2B (cloud sandbox)
  state_store : Redis
  lease       : Redis (shared with state store)
  tracing     : Staso
  framework   : OpenHands
"""

from __future__ import annotations

import asyncio
import os
from redis.asyncio import Redis
import oak_session
import oak_session.openhands
import oak_workspace


# [OAK] Call configure_oak() once at process startup (e.g. FastAPI lifespan).
async def configure_oak() -> None:
    # [OAK] state store
    redis_client = Redis.from_url(os.environ["REDIS_URL"])
    state_store = oak_session.RedisStateStore(redis_client)

    # [OAK] lease coordinator
    lease = oak_session.RedisLease(redis_client)

    # [OAK] trace source
    trace = oak_session.StasoTraceSource(api_key=os.environ["STASO_API_KEY"])

    oak_session.configure(state_store=state_store, lease=lease, trace=trace)


# [OAK] workspace factory used on cold-start / when reconnect fails.
async def _workspace_factory() -> "oak_workspace.Workspace":
    ws = await oak_workspace.create("e2b", api_key=os.environ["E2B_API_KEY"], timeout_ms=900000)
    return ws


# [USER] Build your agent here. Returned object is forwarded to the framework
#        attach() unchanged.
def build_agent() -> object:
    # TODO [USER]: construct your OpenHands agent (LLM, tools, prompt).
    raise NotImplementedError("build_agent() not implemented")


# [OAK] One-call per-request handler. Wire this into your HTTP route.
async def handle_user_message(session_id: str, user_text: str) -> dict[str, object]:
    agent = build_agent()
    async with oak_session.openhands.attach(
        session_id,
        agent=agent,
        workspace_factory=_workspace_factory,
        on_workspace_lost="boot_fresh",
        wait_for_lease=5.0,
    ) as session:
        result = await session.run_turn(user_text)
        if result.status == "waiting_for_confirmation":
            # [USER] approval gate — surface result.pending_action to your UI
            #        and decide approve / reject based on a human signal.
            # For demo purposes we auto-approve.
            result = await session.approve()
        return {
            "status": result.status,
            "messages": [m.content for m in result.messages],
        }


# ---------------------------------------------------------------------------
# Wire-up hint (FastAPI):
#
#     from contextlib import asynccontextmanager
#     from fastapi import FastAPI
#     from oak_setup import configure_oak, handle_user_message
#
#     @asynccontextmanager
#     async def lifespan(app: FastAPI):
#         await configure_oak()
#         yield
#
#     app = FastAPI(lifespan=lifespan)
#
#     @app.post("/chat/{session_id}")
#     async def chat(session_id: str, text: str):
#         return await handle_user_message(session_id, text)
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    async def _main() -> None:
        await configure_oak()
        print(await handle_user_message("local-test", "hello"))

    asyncio.run(_main())
